function visualizeResults(results)
% visualizeResults Visualize PCD results from each methods
% 
% Inputs
%     results     a struct array 

figure; hold on;
scatter(1:N, sort_exact(1:N),...
     'MarkerFaceColor', hex2rgb('073b4c')./255,...
     'AlphaData', sort_exact(1:N),...
     'MarkerFaceAlpha', 'flat',...
     'MarkerEdgeAlpha', 0.0);

scatter(1:N, sort_enlarged_sq(1:N),...
     'MarkerFaceColor', hex2rgb('ffd166')./255,...
     'AlphaData', sort_enlarged_sq(1:N),...
     'MarkerFaceAlpha', 'flat',...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_convex_hull(1:N),...
     'MarkerFaceColor', hex2rgb('06d6a0')./255,...
     'AlphaData', sort_convex_hull(1:N),...
     'MarkerFaceAlpha', 'flat',...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_our_bound(1:N),...
     'MarkerFaceColor', hex2rgb('ef476f')./255,...
     'AlphaData', sort_our_bound(1:N),...
     'MarkerFaceAlpha', 'flat',...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_our_bound_GMM(1:N),...
     'MarkerFaceColor', hex2rgb('118ab2 ')./255,...
     'AlphaData', sort_our_bound_GMM(1:N),...
     'MarkerFaceAlpha', 'flat',...
     'MarkerEdgeAlpha', 0.0);
%  %%
%  figure; hold on;
 markerAlpha = 0.4;
 markerSize = 30;
scatter(1:N, sort_exact(1:N),...
    markerSize,...
     'MarkerFaceColor', hex2rgb('073b4c')./255,...
     'MarkerFaceAlpha',markerAlpha,...
     'MarkerEdgeAlpha', 0.0);

scatter(1:N, sort_enlarged_sq(1:N),...
     markerSize,...
     'MarkerFaceColor', hex2rgb('fb8500')./255,...
     'MarkerFaceAlpha', markerAlpha,...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_convex_hull(1:N),...
    markerSize,...
     'MarkerFaceColor', hex2rgb('06d6a0')./255,...
     'MarkerFaceAlpha',markerAlpha,...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_our_bound(1:N),...
    markerSize,...
     'MarkerFaceColor', hex2rgb('ef476f')./255,...
     'MarkerFaceAlpha', markerAlpha,...
     'MarkerEdgeAlpha', 0.0);
 
scatter(1:N, sort_our_bound_GMM(1:N),...
    markerSize,...
     'MarkerFaceColor', hex2rgb('118ab2 ')./255,...
     'MarkerFaceAlpha', markerAlpha,...
     'MarkerEdgeAlpha', 0.0);


% figure; hold on;
VisualizeFitResult(sort_exact, hex2rgb('073b4c')./255)
% VisualizeFitResult(sort_enlarged_sq,hex2rgb('ffd166')./255)
% plot(1:N, sort_enlarged_sq(1:N), 'Color', hex2rgb('ffd166')./255, 'LineWidth', 2)
VisualizeFitResult(sort_convex_hull, hex2rgb('06d6a0')./255)
% VisualizeFitResult(sort_x_max, 'm')
VisualizeFitResult(sort_our_bound, hex2rgb('ef476f')./255)
VisualizeFitResult(sort_our_bound_GMM, hex2rgb('118ab2 ')./255)
% VisualizeFitResult(sort_enlarged_sq, 'y')

%%
% figure; hold on;
% VisualizeFitResult(sort_convex_hull, hex2rgb('06d6a0')./255)
% Define the "shading"
% Note how each x_points(i) corresponds to y_points(i)

%size 0.1: n=280;n2=344;
%size 1: n=269; n2=354;
n=269;
prob=sort_exact(n);
n2=354;
prob2=sort_exact(n2);

x1_points = [0, 0, n, n];  
y1_points = [0, prob, prob, 0];
color1 = hex2rgb('06d6a0')./255;
a1 = fill(x1_points, y1_points, color1);
a1.FaceAlpha = 0.6;
a1.EdgeAlpha = 0.0;

x2_points = [n, n, n2, n2];  
y2_points = [prob, 1, 1, prob];
color2 =  hex2rgb('118ab2 ')./255;
a2 = fill(x2_points, y2_points, color2);
a2.FaceAlpha = 0.2;
a2.EdgeAlpha = 0.0;
% 
vertical_line = linspace(0, 1, 100);
plot(n*ones(size(vertical_line)), vertical_line, 'Color', hex2rgb('073b4c')./255);

horizontal_line = prob * ones(1, n2);
plot(1:n2, horizontal_line, 'Color', hex2rgb('073b4c')./255);

vertical_line2 = linspace(prob, 1, 100);
plot(n2*ones(size(vertical_line)), vertical_line2, 'Color', hex2rgb('073b4c')./255);

horizontal_line2 = prob2 * ones(1, n2);
plot(1:n2, horizontal_line2, 'Color', hex2rgb('073b4c')./255, 'LineStyle',":", 'LineWidth', 2);

horizontal_line3 = prob * ones(1, N-n2+1);
plot(n2:N, horizontal_line3, 'Color', hex2rgb('073b4c')./255, 'LineStyle',":", 'LineWidth', 2);

horizontal_line4 = prob2 * ones(1, N-n2+1);
plot(n2:N, horizontal_line4, 'Color', hex2rgb('073b4c')./255, 'LineStyle',":", 'LineWidth', 2);

yticks([0 prob  0.2  0.4 prob2  0.6  0.8  1.0])
ylim([0 1])
xlim([1 500])


end